[supervisord]
nodaemon=true
logfile=/usr/src/app/logs/supervisord.log

[program:slskd]
command=/usr/local/bin/slskd --no-auth=true --api-key=%(ENV_SLSKD_API_KEY)s --slsk-username=%(ENV_SLSK_USERNAME)s --slsk-password=%(ENV_SLSK_PASSWORD)s --downloads-dir=/downloads --app-dir=/usr/src/app/slskd-data
autostart=true
autorestart=true
stderr_logfile=/usr/src/app/logs/slskd.err.log
stdout_logfile=/usr/src/app/logs/slskd.out.log

[program:bot]
command=npm start
directory=/usr/src/app
autostart=true
autorestart=true
; Wait for slskd to be ready
startsecs=10
stderr_logfile=/usr/src/app/logs/bot.err.log
stdout_logfile=/usr/src/app/logs/bot.out.log
